[[plugins]]
repo = 'Shougo/dein.vim'

# git
[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

# ファイラ
[[plugins]]
repo = 'Shougo/defx.nvim'

# devicon有効に
[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'kristijanhusak/defx-icons'

[[plugins]]
repo = 'kristijanhusak/defx-git'

# ステータスライン装飾
[[plugins]]
repo = 'itchyny/lightline.vim'

# カラースキーム
[[plugins]]
repo = 'Nequo/vim-allomancer'

[[plugins]]
repo = 'tomasr/molokai'

# カッコ(とか)を閉じる
[[plugins]]
repo = 'cohama/lexima.vim'

# typescript
[[plugins]]
repo = 'Quramy/tsuquyomi'

# シンタックスチェッカ
[[plugins]]
repo = 'vim-syntastic/syntastic'

[[plugins]]
repo = 'neoclide/coc.nvim'

[[plugins]]
repo = 'neoclide/coc-html'

[[plugins]]
repo = 'neoclide/coc-css'

[[plugins]]
repo = 'neoclide/coc-tsserver'

# shell
[[plugins]]
repo = 'Shougo/deol.nvim'

# js
[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'jelera/vim-javascript-syntax'

# Yet Another JavaScript Syntax
[[plugins]]
repo = 'othree/yajs.vim'

# vimでマークダウンをプレビューするためのプラグイン
[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'previm/previm'
hook_add = '''
    autocmd BufRead,BufNewFile *.md  set filetype=markdown
    nnoremap <silent> <C-p> :PrevimOpen<CR>
    let g:vim_markdown_folding_disabled=1
    let g:previm_enable_realtime=1
'''

[[plugins]]
repo = 'tyru/open-browser.vim'

# jsxのインデント
[[plugins]]
repo = 'MaxMEllon/vim-jsx-pretty'

# tsx
[[plugins]]
repo = 'leafgarland/typescript-vim'

# ESLint
[[plugins]]
repo = 'dense-analysis/ale'

# PowerShell
[[plugins]]
repo = 'coc-extensions/coc-powershell'

# github copilot
[[plugins]]
repo = 'github/copilot.vim'

# fuzzy finder
[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
