[[plugins]]
repo = 'Shougo/dein.vim'

# git
[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

# ファイラ
[[plugins]]
repo = 'Shougo/defx.nvim'

# 補完
[[plugins]]
repo = 'Shougo/ddc.vim'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'vim-denops/denops-helloworld.vim'

# devicon有効に
[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'kristijanhusak/defx-icons'

[[plugins]]
repo = 'kristijanhusak/defx-git'

# ステータスライン装飾
[[plugins]]
repo = 'itchyny/lightline.vim'

# カラースキーム
[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'neoclide/coc.nvim'

[[plugins]]
repo = 'neoclide/coc-html'

[[plugins]]
repo = 'neoclide/coc-css'

[[plugins]]
repo = 'neoclide/coc-tsserver'

# shell
[[plugins]]
repo = 'Shougo/deol.nvim'

# vimでマークダウンをプレビューするためのプラグイン
[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'previm/previm'
hook_add = '''
    autocmd BufRead,BufNewFile *.md  set filetype=markdown
    nnoremap <silent> <F12> :PrevimOpen<CR>
    let g:vim_markdown_folding_disabled=1
    let g:previm_enable_realtime=1
'''

[[plugins]]
repo = 'tyru/open-browser.vim'

# jsxのインデント
[[plugins]]
repo = 'MaxMEllon/vim-jsx-pretty'

# tsx
[[plugins]]
repo = 'leafgarland/typescript-vim'

# ESLint
# TypeScriptReactの設定の模索が必要そう 一旦除外
#[[plugins]]
#repo = 'dense-analysis/ale'

# PowerShell
[[plugins]]
repo = 'coc-extensions/coc-powershell'

# github copilot
[[plugins]]
repo = 'github/copilot.vim'

# fuzzy finder
[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

# color preview
[[plugins]]
repo = 'gorodinskiy/vim-coloresque'

# emmet
[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'phpactor/phpactor'
